[package]
name = "rpc-ext"
version = "0.1.0"
authors = ["Kevin Wang <wy721@qq.com>"]
edition = "2018"

[dependencies]
# third-party dependencies
serde = { version = "1.0.102", features = ["derive"] }
derive_more = "0.99.0"
jsonrpc-derive = "15.1"
jsonrpc-core = "15.1"
jsonrpc-core-client = "15.1"
impl-serde = "0.3"

# primitives
sp-runtime = { version = "3.0.0", path = "../../../primitives/runtime" }
sp-blockchain = { version = "3.0.0", path = "../../../primitives/blockchain" }
sp-api = { version = "3.0.0", path = "../../../primitives/api" }

# client dependencies
sc-client-api = { version = "3.0.0", path = "../../../client/api" }

# node-specific dependencies
node-rpc = { version = "2.0.0", path = "../rpc" }

